global_options:
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          explicit_to_json: true
      freezed:
        options:
          union_key: type
          format: false
