name: flutter_application_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  riverpod_hook_mutation: ^0.0.2
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  awesome_dio_interceptor: ^1.2.0
  riverpod_hook_extensions: ^0.0.4
  drift: ^2.19.1
  drift_flutter: ^0.1.0
  supabase_flutter: ^2.5.9
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  retrofit_generator: ^8.1.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  drift_dev: ^2.19.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env


scripts:
  g: 
    $script: flutter pub run build_runner build --delete-conflicting-outputs && flutter pub get
    $description: "Generate files"
    $usage: rps g
  fix-format:
    $script: dart fix --apply && dart format -o write ./lib
    $description: "Fix format"
    $usage: rps fix-format
  uninstall:
    android: 
      $script: adb uninstall com.example.flutter_application_example
      $description: "Uninstall android"
      $usage: rps uninstall android